# Generated by Django 2.0.2 on 2018-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tz_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='跳转链接')),
                ('pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片地址')),
                ('des', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '导航广告',
                'verbose_name_plural': '导航广告',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='房间名称')),
                ('apply_money', models.IntegerField(verbose_name='报名费')),
                ('pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('max_count', models.CharField(blank=True, max_length=20, null=True, verbose_name='最大人数')),
                ('current_count', models.CharField(blank=True, max_length=128, null=True, verbose_name='当前人数')),
                ('apply', models.ManyToManyField(blank=True, null=True, related_name='room', to='tz_user.TZUser', verbose_name='报名信息')),
            ],
            options={
                'verbose_name': '房间信息',
                'verbose_name_plural': '房间信息',
            },
        ),
    ]
