# Generated by Django 2.0.2 on 2018-05-28 15:19

from django.db import migrations, models
import django.db.models.deletion
import game_room.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tz_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyDetail',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('id', models.CharField(default=game_room.models.order_oid, max_length=250, primary_key=True, serialize=False, verbose_name='订单id')),
                ('trade_id', models.CharField(max_length=128, verbose_name='支付宝订单ID')),
                ('nickname', models.CharField(max_length=128, verbose_name='游戏角色名')),
                ('gmt_payment', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('money', models.IntegerField(verbose_name='报名金额')),
                ('status', models.IntegerField(choices=[(0, '已完成'), (1, '待支付'), (2, '支付中'), (3, '支付失败')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '报名明细',
                'verbose_name_plural': '报名明细',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='跳转链接')),
                ('pic', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片地址')),
                ('des', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '导航广告',
                'verbose_name_plural': '导航广告',
            },
        ),
        migrations.CreateModel(
            name='CheckWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('room_id', models.IntegerField(verbose_name='房间ID')),
                ('game_user_name', models.CharField(max_length=32, verbose_name='游戏昵称')),
                ('img', models.CharField(max_length=512, verbose_name='状态')),
                ('checked', models.IntegerField(choices=[(0, '申请拒绝'), (1, '审核通过')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '报名明细',
                'verbose_name_plural': '报名明细',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='游戏名称')),
                ('des', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('is_hot', models.IntegerField(default=0, verbose_name='热门')),
            ],
            options={
                'verbose_name': '游戏列表',
                'verbose_name_plural': '游戏列表',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('index', models.IntegerField(verbose_name='排名')),
            ],
            options={
                'verbose_name': '房间排行',
                'verbose_name_plural': '房间排行',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='房间名称')),
                ('apply_money', models.IntegerField(verbose_name='报名费')),
                ('hot', models.BooleanField(default=False, verbose_name='热门')),
                ('status', models.IntegerField(choices=[(1, '未开始'), (2, '开始报名'), (3, '结束报名'), (4, '游戏结束')], default=1, verbose_name='状态')),
                ('pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('des', models.TextField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('max_count', models.IntegerField(verbose_name='最大人数')),
                ('current_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='当前人数')),
                ('start_time', models.DateTimeField(verbose_name='开始报名时间')),
                ('end_time', models.DateTimeField(verbose_name='结束报名时间')),
                ('game_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='游戏密码')),
                ('apply', models.ManyToManyField(blank=True, null=True, related_name='room', to='tz_user.TZUser', verbose_name='报名信息')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='game_room.Game', verbose_name='游戏名称')),
            ],
            options={
                'verbose_name': '房间信息',
                'verbose_name_plural': '房间信息',
            },
        ),
        migrations.AddField(
            model_name='rank',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='game_room.Room'),
        ),
        migrations.AddField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tz_user.TZUser'),
        ),
        migrations.AddField(
            model_name='applydetail',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_detail', to='game_room.Room'),
        ),
        migrations.AddField(
            model_name='applydetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tz_user.TZUser'),
        ),
    ]
