# Generated by Django 2.0.2 on 2018-02-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tz_user', '0004_auto_20180221_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default='0', max_length=2, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='房间名称')),
                ('apply_money', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='报名费')),
                ('max_count', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='最大人数')),
                ('current_count', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='当前人数')),
                ('apply', models.ManyToManyField(related_name='room', to='tz_user.TZUser')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
