# Generated by Django 2.0.2 on 2018-03-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='游戏名称')),
                ('des', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('is_hot', models.IntegerField(default=0, verbose_name='图片地址')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='game_room.Game'),
        ),
    ]
