# Generated by Django 2.0.2 on 2018-02-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间信息', 'verbose_name_plural': '房间信息'},
        ),
        migrations.AlterField(
            model_name='room',
            name='apply',
            field=models.ManyToManyField(blank=True, null=True, related_name='room', to='tz_user.TZUser', verbose_name='报名信息'),
        ),
        migrations.AlterField(
            model_name='room',
            name='apply_money',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='报名费'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_count',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='当前人数'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='最大人数'),
        ),
    ]
