# Generated by Django 2.0.2 on 2018-06-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='apply_money',
            field=models.IntegerField(verbose_name='报名卡数量'),
        ),
    ]
