# Generated by Django 2.0.2 on 2018-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0002_auto_20180303_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
