# Generated by Django 2.0.2 on 2018-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0002_auto_20180603_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='apply_money',
            field=models.IntegerField(default=1, verbose_name='报名卡数量'),
        ),
    ]
