# Generated by Django 2.0.2 on 2018-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0003_room_hot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '游戏列表', 'verbose_name_plural': '游戏列表'},
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '进行中'), (2, '已结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_hot',
            field=models.IntegerField(default=0, verbose_name='热门'),
        ),
    ]
