# Generated by Django 2.0.2 on 2018-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0004_auto_20180221_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='apply_money',
            field=models.IntegerField(default=20, verbose_name='报名费'),
            preserve_default=False,
        ),
    ]
