# Generated by Django 2.0.2 on 2018-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0004_auto_20180303_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='des',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前人数'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_count',
            field=models.IntegerField(default=100, verbose_name='最大人数'),
            preserve_default=False,
        ),
    ]
