# Generated by Django 2.0.2 on 2018-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0005_auto_20180221_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default='0', max_length=2, verbose_name='是否删除')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='链接')),
                ('des', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '导航广告',
                'verbose_name_plural': '导航广告',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='pic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址'),
        ),
    ]
