# Generated by Django 2.0.2 on 2018-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0005_auto_20180303_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='des',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
    ]
