# Generated by Django 2.0.2 on 2018-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0006_auto_20180221_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='跳转链接'),
        ),
    ]
