# Generated by Django 2.0.2 on 2018-03-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0003_auto_20180304_0447'),
        ('game_room', '0007_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('money', models.IntegerField(verbose_name='报名金额')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_detail', to='game_room.Room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tz_user.TZUser')),
            ],
            options={
                'verbose_name': '报名明细',
                'verbose_name_plural': '报名明细',
            },
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '房间排行', 'verbose_name_plural': '房间排行'},
        ),
    ]
