# Generated by Django 2.0.2 on 2018-03-19 14:25

from django.db import migrations, models
import game_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0010_auto_20180318_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='applydetail',
            name='gmt_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='applydetail',
            name='trade_id',
            field=models.CharField(default='', max_length=128, verbose_name='支付宝订单ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='id',
            field=models.CharField(default=game_room.models.order_oid, max_length=256, primary_key=True, serialize=False, verbose_name='订单id'),
        ),
    ]
