# Generated by Django 2.0.2 on 2018-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0011_auto_20180319_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '已结束')], default=1, verbose_name='状态'),
        ),
    ]
