# Generated by Django 2.0.2 on 2018-04-22 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0012_auto_20180320_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 11, 41, 34, 837350, tzinfo=utc), verbose_name='结束报名时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='game_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 11, 41, 39, 813135, tzinfo=utc), verbose_name='开始报名时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '开始报名'), (3, '结束报名'), (4, '游戏结束')], default=1, verbose_name='状态'),
        ),
    ]
