# Generated by Django 2.0.2 on 2018-04-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0014_checkwinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='apply',
        ),
        migrations.RemoveField(
            model_name='room',
            name='apply_money',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='des',
        ),
        migrations.RemoveField(
            model_name='room',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='game',
        ),
        migrations.RemoveField(
            model_name='room',
            name='game_password',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
