# Generated by Django 2.0.2 on 2018-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0015_auto_20180424_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='apply_money',
            field=models.IntegerField(default=0, verbose_name='报名费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='热门'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '开始报名'), (3, '结束报名'), (4, '游戏结束')], default=1, verbose_name='状态'),
        ),
    ]
