# Generated by Django 2.0.2 on 2018-04-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0005_tzuser_card'),
        ('game_room', '0018_auto_20180424_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='apply',
            field=models.ManyToManyField(blank=True, null=True, related_name='room', to='tz_user.TZUser', verbose_name='报名信息'),
        ),
    ]
