# Generated by Django 2.0.2 on 2018-04-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0019_room_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='applydetail',
            name='nickname',
            field=models.CharField(default='', max_length=128, verbose_name='游戏角色名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='game_room.Game', verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='room',
            name='game_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='游戏密码'),
        ),
    ]
