# Generated by Django 2.0.2 on 2018-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_room', '0020_auto_20180424_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkwinner',
            options={'verbose_name': '报名明细', 'verbose_name_plural': '报名明细'},
        ),
        migrations.AddField(
            model_name='checkwinner',
            name='checked',
            field=models.IntegerField(choices=[(0, '申请拒绝'), (1, '审核通过')], default=0, verbose_name='状态'),
        ),
    ]
