# Generated by Django 2.0.2 on 2018-02-22 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TZUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户名')),
                ('tel', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='电话号码')),
                ('alipay_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付宝姓名')),
                ('alipay_account', models.CharField(blank=True, max_length=128, null=True, verbose_name='支付宝账号')),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='开户行')),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行卡号')),
                ('bank_card_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='银行户名')),
                ('money', models.IntegerField(default=0, verbose_name='余额')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tz_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
