# Generated by Django 2.0.2 on 2018-05-28 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tz_user.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='TZUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户名')),
                ('tel', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='电话号码')),
                ('alipay_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付宝姓名')),
                ('alipay_account', models.CharField(blank=True, max_length=128, null=True, verbose_name='支付宝账号')),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='开户行')),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行卡号')),
                ('bank_card_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='银行户名')),
                ('money', models.IntegerField(default=0, verbose_name='余额')),
                ('invite_code', models.IntegerField(default=tz_user.utils.invite_code, unique=True)),
                ('card', models.IntegerField(default=0, verbose_name='激活卡')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tz_user', to=settings.AUTH_USER_MODEL)),
                ('invite_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='tz_user.TZUser')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='mail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='tz_user.TZUser'),
        ),
    ]
