# Generated by Django 2.0.2 on 2018-02-20 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TZUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default='0', max_length=2, verbose_name='是否删除')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户名')),
                ('tel', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='电话号码')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
