# Generated by Django 2.0.2 on 2018-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tzuser',
            name='card',
            field=models.IntegerField(default=0, verbose_name='报名卡'),
        ),
    ]
