# Generated by Django 2.0.2 on 2018-03-03 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tz_user.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tz_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tzuser',
            name='invite_code',
            field=models.IntegerField(default=tz_user.utils.invite_code, unique=True),
        ),
        migrations.AddField(
            model_name='tzuser',
            name='invite_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite', to='tz_user.TZUser'),
        ),
    ]
