# Generated by Django 2.0.2 on 2018-06-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0002_auto_20180603_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='tzuser',
            name='gain',
            field=models.IntegerField(default=0, verbose_name='累计盈利'),
        ),
    ]
