# Generated by Django 2.0.2 on 2018-03-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0003_auto_20180304_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='tz_user.TZUser'),
        ),
    ]
