# Generated by Django 2.0.2 on 2018-02-21 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0003_auto_20180221_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tzuser',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tz_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
