# Generated by Django 2.0.2 on 2018-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0003_tzuser_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tzuser',
            name='total',
            field=models.IntegerField(default=0, verbose_name='已赚取奖励'),
        ),
    ]
