# Generated by Django 2.0.2 on 2018-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0004_auto_20180320_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tzuser',
            name='card',
            field=models.IntegerField(default=0, verbose_name='激活卡'),
        ),
    ]
