# Generated by Django 2.0.2 on 2018-02-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0004_auto_20180221_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tzuser',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='tzuser',
            name='alipay_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支付宝账号'),
        ),
        migrations.AlterField(
            model_name='tzuser',
            name='alipay_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='支付宝姓名'),
        ),
        migrations.AlterField(
            model_name='tzuser',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='银行卡号'),
        ),
        migrations.AlterField(
            model_name='tzuser',
            name='bank_card_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='银行户名'),
        ),
        migrations.AlterField(
            model_name='tzuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='开户行'),
        ),
    ]
