# Generated by Django 2.0.2 on 2018-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0005_auto_20180221_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tzuser',
            name='is_delete',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default='0', max_length=2, verbose_name='是否删除'),
        ),
    ]
