# Generated by Django 2.0.2 on 2018-06-12 14:43

from django.db import migrations, models
import tz_user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tz_user', '0005_tzuser_add_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tzuser',
            name='gain',
        ),
        migrations.AlterField(
            model_name='tzuser',
            name='invite_code',
            field=models.IntegerField(default=tz_user.utils.invite_code, unique=True, verbose_name='邀请码'),
        ),
    ]
